"""empty message

Revision ID: d02552af4e2e
Revises: 303885f99401
Create Date: 2019-06-04 20:25:44.383076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd02552af4e2e'
down_revision = '303885f99401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('password', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'password')
    # ### end Alembic commands ###
